@echo off
echo Borrando entorno antiguo...
rmdir /s /q venv_traductor
echo Creando entorno nuevo con Python 3.10...
py -3.10 -m venv venv_traductor
call venv_traductor\Scripts\activate.bat
echo Instalando PyTorch CUDA 12.1 real (forzando version)...
pip install torch==2.5.1+cu121 torchvision==0.20.1+cu121 --extra-index-url https://download.pytorch.org/whl/cu121
echo Instalando Unsloth...
pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
echo Instalando dependencias criticas de IA...
pip install --no-deps xformers trl peft accelerate bitsandbytes
echo Instalando dependencias del Servidor Puente...
pip install flask flask-cors requests pyperclip
echo.
echo ==========================================
echo TODO TERMINADO. ENTORNO LISTO PARA ENTRENAR.
echo ==========================================
