import sys
import json
import os

def extraer_xunity(ruta_archivo, ruta_salida):
    if not os.path.exists(ruta_archivo):
        print(f"Error: No se encuentra {ruta_archivo}")
        return

    pares = []
    with open(ruta_archivo, 'r', encoding='utf-8-sig', errors='ignore') as f:
        for linea in f:
            linea = linea.strip()
            if not linea or linea.startswith('//'):
                continue
            
            # XUnity format is usually Original=Translated
            # We split by the first '='
            if '=' in linea:
                partes = linea.split('=', 1)
                if len(partes) == 2:
                    ingles = partes[0].strip()
                    espanol = partes[1].strip()
                    
                    if ingles and espanol and ingles != espanol:
                        pares.append({
                            "ingles": ingles,
                            "espanol": espanol,
                            "contexto": "xunity_autotranslator"
                        })

    # Eliminar duplicados exactos
    vistos = set()
    datos_unicos = []
    for item in pares:
        tupla = (item['ingles'], item['espanol'])
        if tupla not in vistos:
            vistos.add(tupla)
            datos_unicos.append(item)

    with open(ruta_salida, 'w', encoding='utf-8') as f_out:
        for item in datos_unicos:
            f_out.write(json.dumps(item, ensure_ascii=False) + '\n')

    print(f"\n¡Éxito! Se han extraído {len(datos_unicos)} frases bilingües únicas.")
    print(f"Guardado en: {ruta_salida}")

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Uso: python extraer_textos_xunity.py <ruta_AutoGeneratedTranslations.txt> <archivo_salida.jsonl>")
        sys.exit(1)
        
    ruta = sys.argv[1]
    salida = sys.argv[2]
    print(f"Analizando {ruta}...")
    extraer_xunity(ruta, salida)
